[package]
org = "ballerinax"
name = "module_ballerinax_netsuite"
version = "0.9.2"
authors = ["Ballerina"]
repository = "https://github.com/ballerina-platform/module-ballerinax-netsuite"
keywords = ["NetSuite", "Finance", "Integration"]
license = ["Apache-2.0"]


[build-options]
observabilityIncluded = true
