[package]
org = "ballerinax"
name = "netsuite"
version = "0.9.6-SNAPSHOT"
authors = ["Ballerina"]
repository = "https://github.com/ballerina-platform/module-ballerinax-netsuite"
keywords = ["business management/erp", "cost/paid"]
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true
