[package]
org = "ballerinax"
name = "netsuite"
version = "2.0.0"
authors = ["Ballerina"]
repository = "https://github.com/ballerina-platform/module-ballerinax-netsuite"
keywords = ["Business Management/ERP", "Cost/Paid"]
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true
