[[dependency]]
org = "ballerina"
name = "crypto"
version = "1.1.0-beta.3"

[[dependency]]
org = "ballerina"
name = "uuid"
version = "0.10.0-beta.3"

[[dependency]]
org = "ballerina"
name = "http"
version = "1.1.0-beta.3"

[[dependency]]
org = "ballerina"
name = "xmldata"
version = "1.1.0-beta.3"

[[dependency]]
org = "ballerina"
name = "os"
version = "0.8.0-beta.3"

[[dependency]]
org = "ballerina"
name = "log"
version = "1.1.0-beta.3"

[[dependency]]
org = "ballerina"
name = "time"
version = "2.0.0-beta.3"

[[dependency]]
org = "ballerina"
name = "regex"
version = "0.7.0-beta.3"
