name: CI

on:
  push:
    branches:
      - '**'
  repository_dispatch:
    types:
      check_connector_for_breaking_changes

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action/@nightly
              with:
                  args:
                      pack ./netsuite
            - name: Ballerina Test
              uses: ballerina-platform/ballerina-action/@nightly
              with:
                  args:
                      test --test-report --code-coverage --coverage-format=xml ./netsuite
              env:
                  NS_BASE_URL: ${{ secrets.BASEURL }}
                  NS_TOKEN_SECRET: ${{ secrets.TOKENSECRET }}
                  NS_TOKEN: ${{ secrets.TOKEN }}
                  NS_CLIENT_ID: ${{ secrets.CONSUMERID }}
                  NS_CLIENT_SECRET: ${{ secrets.CONSUMERSECRET }}
                  NS_ACCOUNTID: ${{secrets.ACCOUNTID}}

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v3

            - name: Alert notifier on failure
              if: failure() && (github.event.action == 'check_connector_for_breaking_changes')
              run: |
                curl -X POST \
                'https://api.github.com/repos/ballerina-platform/ballerina-release/dispatches' \
                --header 'Accept: application/vnd.github.v3+json' \
                --header 'Authorization: Bearer ${{ secrets.BALLERINA_BOT_TOKEN }}' \
                --data-raw '{
                  "event_type": "notify-ballerinax-connector-build-failure",
                  "client_payload": {
                    "repoName": "module-ballerinax-netsuite",
                    "workflow": "CI"
                  }
                }'                 
