name: Deployment

on:
    release:
        types: [published]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action/@master
              with:
                  args:
                      build -c
              env:
                  NS_BASE_URL: ${{ secrets.BASEURL }}
                  NS_TOKEN_SECRET: ${{ secrets.TOKENSECRET }}
                  NS_TOKEN: ${{ secrets.TOKEN }}
                  NS_CLIENT_ID: ${{ secrets.CONSUMERID }}
                  NS_CLIENT_SECRET: ${{ secrets.CONSUMERSECRET }}
                  NS_ACCOUNTID: ${{secrets.ACCOUNTID}}
            - name: Ballerina Push
              uses: ballerina-platform/ballerina-action/@master
              with:
                  args:
                      push
              env:
                  BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_ACCESS_TOKEN }}
